name: Bridgewars
version: 1.0
author: Schlog
main: bridgewars.Main
description: Bridgewars - The Plugin

commands:
  startgame:
    aliases: [sg]
    description: Begins a game of Bridgewars.
  endgame:
    aliases: [eg]
    description: Manually ends a game of Bridgewars.
  joingame:
    aliases: [join]
    description: Join a currently active game of Bridgewars.
  menu:
    aliases: [bw]
    description: Open up the settings menu.
  jointeam:
    aliases: [team]
    description: Manually join a team.
  giveitem:
    aliases: [gi]
    description: Give yourself a Bridgewars item.
  savemap:
    aliases: [save]
    description: Saves the current Bridgewars map to a file.
  loadmap:
    aliases: [load]
    description: Loads a desired Bridgewars map, if it exists.
  clearmap:
    aliases: [cm]
    description: Clears the Bridgewars map.
  maplist:
    aliases: [maps]
    description: Lists all existing Bridgewars maps.
  deletemap:
    aliases: [delete]
    description: Deletes an existing map file.
  overwritemap:
    aliases: [overwrite]
    description: Overwrites an existing map file.
  warp:
    aliases: [hub]
    description: Warp to a location.
  editmode:
    aliases: [edit]
    description: Toggles Edit Mode.
  leave:
    aliases: [l]
    description: Leave the Bridgewars game.
  fly:
    description: Toggle flight.
  debug:
    description: debug
  label:
    description: Places floating text at your feet.