name: Bridgewars
version: 1.0
author: Schlog
main: bridgewars.Main
description: Bridgewars - The Plugin

commands:
  startgame:
    aliases: [sg]
    description: Begins a game of Bridgewars.
  endgame:
    aliases: [eg]
    description: Manually ends a game of Bridgewars.
  joingame:
    aliases: [join]
    description: Join a currently active game of Bridgewars.
  menu:
    aliases: [bw]
    description: Open up the settings menu.
  jointeam:
    aliases: [team]
    description: Manually join a team.
  giveitem:
    aliases: [gi]
    description: Give yourself a Bridgewars item.
  savemap:
    aliases: [save]
    description: Saves the current Bridgewars map to a file.
  loadmap:
    aliases: [load]
    description: Loads a desired Bridgewars map, if it exists.
  clearmap:
    aliases: [cm]
    description: Clears the Bridgewars map.
  maplist:
    aliases: [maps]
    description: Lists all existing Bridgewars maps.
  deletemap:
    aliases: [delete]
    description: Deletes an existing map file.
  overwritemap:
    aliases: [overwrite]
    description: Overwrites an existing map file.
  warp:
    aliases: [hub]
    description: Warp to a location.
  editmode:
    aliases: [edit]
    description: Toggles Edit Mode.
  leave:
    aliases: [l]
    description: Leave the Bridgewars game.
  fly:
    description: Toggle flight.
  debug:
    description: debug
  label:
    description: Places floating text at your feet.
  transform:
    aliases: [d]
    description: become another player
  permission:
    aliases: [perm]
    description: grants a player a permission
  gm:
    aliases: [gmc, gms, gma, gmsp]
    description: faster gamemode change
  chat:
    aliases: [tc, ac]
    description: set your chat settings
  whisper:
    aliases: [w, msg]
    description: /tell but better lmao

permissions:
  trusted:
    description: gives access to trusted
    default: op
    children:
      trusted.worldedit: true
      trusted.gamemode: true
      trusted.fly: true
      trusted.label: true
      trusted.endgame: true
      trusted.settings: true
  trusted.worldedit:
    description: allows usage of worldedit
    default: op
  trusted.gamemode:
    description: allows setting of own gamemode outside of a game
    default: op
  trusted.fly:
    description: allows /fly in lobby
    default: op
  trusted.label:
    description: allows use of /label outside of a game
    default: op
  trusted.endgame:
    description: allows player to end game manually
    default: op
  trusted.settings:
    description: allows player to edit game settings
    default: op
