name: Bridgewars
version: 1.0
author: Schlog
main: bridgewars.Main
description: Bridgewars - The Plugin

commands:
  startgame:
    aliases: [sg, start]
    usage: /startgame /start /sg
    description: Begins a game of Bridgewars.
  endgame:
    aliases: [eg, end]
    usage: /endgame /end /eg
    description: Manually ends a game of Bridgewars.
  joingame:
    aliases: [join, j]
    usage: /joingame /join /j
    description: Join a currently active game of Bridgewars.
  menu:
    aliases: [bridgewars, bw, m]
    usage: /menu /bridgewars /bw /m
    description: Open up the settings menu.
  jointeam:
    aliases: [team]
    usage: /team <red | blue | green | yellow>
    description: Manually join a team.
  giveitem:
    aliases: [gi, i]
    usage: /giveitem <item> [amount]
    description: Give yourself a Bridgewars item.
  savemap:
    aliases: [save]
    usage: /save <map name>
    description: Saves the current Bridgewars map to a file.
  loadmap:
    aliases: [load]
    usage: /load <map name>
    description: Loads a desired Bridgewars map, if it exists.
  clearmap:
    aliases: [c]
    usage: /clearmap /c
    description: Clears the Bridgewars map.
  maplist:
    aliases: [maps]
    usage: /maplist /maps
    description: Lists all existing Bridgewars maps.
  deletemap:
    aliases: [delete]
    usage: /delete <map name>
    description: Deletes an existing map file.
  overwritemap:
    aliases: [overwrite]
    usage: /overwrite <map name>
    description: Overwrites an existing map file.
  warp:
    aliases: [hub, l]
    usage: /warp <location>
    description: Warp to a location.
  editmode:
    aliases: [edit]
    usage: /editmode /edit
    description: Toggles Edit Mode.
  leave:
    aliases: [quit, q]
    usage: /leave /quit /q
    description: Leave the Bridgewars game.
  fly:
    aliases: [f]
    usage: /fly /f
    description: Toggle flight in the main lobby.
  debug:
    aliases: []
    usage: /debug
    description: Debug command solely for testing new features.
  label:
    aliases: [text]
    usage: /label [vertical offset | undo] <text>
    description: Places floating text at your location.
  transform:
    aliases: []
    usage: /transform <player name>
    description: Changes your skin and name to match the target player.
  permission:
    aliases: [perm]
    usage: /perm <give | take | get | clear> <player name> <permission>
    description: Alter a player's bridgewars permissions. (trusted, trusted.fly, trusted.worldedit, trusted. gamemode, trusted.label, trusted.endgame, trusted.settings)
  gm:
    aliases: [gmc, gms, gma, gmsp]
    usage: /gmc /gms /gma /gmsp
    description: Shorthand for quickly switching gamemodes.
  chat:
    aliases: [tc, ac]
    usage: /tc /ac
    description: Switch between team chat and all chat
  whisper:
    aliases: [w, msg, pm, dm]
    usage: /whisper /msg /w /pm /dm
    description: Alternatives for /tell, cannot be spied on
  playersetting:
    aliases: [ps]
    usage: /playersetting <player> <setting> <value>
    description: Manually edit a hotbar, killstreak, or other setting to be any value.

permissions:
  trusted:
    description: gives access to trusted
    default: op
    children:
      trusted.worldedit: true
      trusted.gamemode: true
      trusted.fly: true
      trusted.label: true
      trusted.endgame: true
      trusted.settings: true
  trusted.worldedit:
    description: allows usage of worldedit
    default: op
  trusted.gamemode:
    description: allows setting of own gamemode outside of a game
    default: op
  trusted.fly:
    description: allows /fly in lobby
    default: op
  trusted.label:
    description: allows use of /label outside of a game
    default: op
  trusted.endgame:
    description: allows player to end game manually
    default: op
  trusted.settings:
    description: allows player to edit game settings
    default: op
